// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {
    '1': { path: '/', parentId: '@@/global-layout', id: '1' },
    '@@/global-layout': { id: '@@/global-layout', path: '/', isLayout: true },
  } as const;
  return {
    routes,
    routeComponents: {
      '1': React.lazy(() => import(/* webpackChunkName: "layouts__index" */ '@/layouts/index.tsx')),
      '@@/global-layout': React.lazy(
        () =>
          import(
            /* webpackChunkName: "layouts__index" */ '/Users/songjun/Workspace/github/developer-assistant/src/renderer/layouts/index.tsx'
          ),
      ),
    },
  };
}
