import { Category } from '../../types';
import { yamlParser, yamlAstParserParser } from './yaml';

export const yaml: Category = {
  id: 'yaml',
  displayName: 'YAML',
  parsers: [yamlParser, yamlAstParserParser],
  codeExample: `
name: astexplorer
version: 1.0.0
description: A web tool to explore the ASTs generated by various parsers.
scripts:
  start: npm start
  build: npm run build
`,
};
